mu-editor/pup

.github/workflows/build-docs.yml
.github/workflows/python-package.yml

First GitHub Action: build Sphinx docs.

---

setup.py
src/pup/api.py
src/pup/dispatcher.py
src/pup/plugins/dirs.py
src/pup/plugins/mac/app_bundle.py
src/pup/plugins/mac/dirs.py
src/pup/plugins/mac/steps.py
src/pup/plugins/pip_install.py
src/pup/plugins/python_runtime.py
src/pup/plugins/win/dirs.py
src/pup/plugins/win/steps.py

Directories API + macOS/Windows plugins.

---

setup.py
src/pup/api.py
src/pup/dispatcher.py
src/pup/plugins/download.py

Cached downloads API and plugin in place.

---

setup.py
src/pup/dispatcher.py
src/pup/plugins/mac/steps.py
src/pup/plugins/pip_install.py
src/pup/plugins/python_runtime.py

Cross-platform plugin step names now pup. prefixed.

---

setup.py
src/pup/api.py
src/pup/context.py
src/pup/dispatcher.py
src/pup/plugins/metadata.py

Packaging context now holds src package metadata.

---

setup.py
src/pup/plugins/mac/app_bundle.py
src/pup/plugins/mac/app_bundle_template/cookiecutter.json
src/pup/plugins/mac/app_bundle_template/{{cookiecutter.app_bundle_name}}.app/Contents/Info.plist
src/pup/plugins/mac/app_bundle_template/{{cookiecutter.app_bundle_name}}.app/Contents/MacOS/{{cookiecutter.launcher_name}}
src/pup/plugins/mac/app_bundle_template/{{cookiecutter.app_bundle_name}}/Info.plist

macOS templated App Bundle generation

---

setup.py
src/pup/plugins/python_runtime.py

Minimal working version of Python runtime extraction.

---

src/pup/context.py
src/pup/plugins/common.py
src/pup/plugins/mac/app_bundle.py
src/pup/plugins/mac/app_bundle_template/{{cookiecutter.app_bundle_name}}.app/Contents/MacOS/{{cookiecutter.launcher_name}}
src/pup/plugins/metadata.py
src/pup/plugins/pip_install.py
src/pup/plugins/python_runtime.py

Minimal pip install step implementation

---

src/pup/__main__.py
src/pup/api.py
src/pup/context.py
src/pup/plugins/mac/app_bundle.py
src/pup/plugins/mac/app_bundle_template/{{cookiecutter.app_bundle_name}}.app/Contents/MacOS/{{cookiecutter.launcher_name}}

CLI/API now allows overriding the launch module name.

---

setup.py
src/pup/plugins/pip_install.py
src/pup/plugins/python_runtime.py
src/pup/plugins/win/dist_layout.py
src/pup/plugins/win/dist_layout_template/{{cookiecutter.app_name}} {{cookiecutter.version}}/{{cookiecutter.app_name}}.vbs
src/pup/plugins/win/steps.py

Windows packaging minimal implementation.

---

src/pup/plugins/python_runtime.py

Drop hard-coded, semi-hacked-POC runtime cleanups.

---

CHANGELOG.rst
docs/newsfragments/.gitignore
docs/source/conf.py
pyproject.toml
src/pup/__init__.py

Release 1.0.0a2

---

setup.py
src/pup/context.py
src/pup/plugins/install_cleanup.py
src/pup/plugins/mac/steps.py
src/pup/plugins/pip_install.py
src/pup/plugins/python_runtime.py
src/pup/plugins/win/dist_layout.py
src/pup/plugins/win/dist_layout_template/{{cookiecutter.app_name}} {{cookiecutter.version}}/{{cookiecutter.app_name}}.vbs
src/pup/plugins/win/steps.py

Remove unnecessary files for distribution

---

src/pup/plugins/install_cleanup.py

Much simpler library module compilation.

---

docs/newsfragments/52.other
src/pup/__main__.py
src/pup/logs.py

Simpler logs messages when directed at a TTY

---

docs/newsfragments/58.other
src/pup/__main__.py

Changed the default logging level to INFO.

---

docs/newsfragments/51.other
src/pup/__main__.py

Log exception tracebacks at CRITICAL level.

---

setup.py
src/pup/context.py
src/pup/plugins/mac/app_bundle.py
src/pup/plugins/mac/notarize.py
src/pup/plugins/mac/steps.py

Notarize macOS app bundles

---

src/pup/plugins/mac/sign.py

CHANGES:
* macOS signing now requires the `PUP_SIGNING_IDENTITY` environment variable to be defined (before it would work without it, producing ad-hoc signed things which, AFAICT, do not serve our purpose).
* Loudly complains about that, somehow guiding early users (or myself, in two weeks time!) in setting it.
Yet another contribution to #43.

Minor macOS signing UI improvement

---

docs/source/development.rst

Updated development docs.

---

README.rst
docs/source/conf.py
src/pup/__init__.py
src/pup/__main__.py
src/pup/api.py

Renamed pup: now called "Pluggable Micro Packager".

---

README.rst
docs/source/foreword.rst
docs/source/toc.rst

Add minimal usage documentation

---

CHANGELOG.rst
docs/newsfragments/41.bug
docs/newsfragments/51.other
docs/newsfragments/52.other
docs/newsfragments/58.other
src/pup/__init__.py

Bumped version to 1.0.0a3.

---

MANIFEST.in
setup.py
src/pup/plugins/mac/app_bundle.py
src/pup/plugins/mac/app_bundle_template/{{cookiecutter.app_bundle_name}}.app/Contents/Resources/.gitignore

Bundle cookiecutter templates into packaged pup.

---

CHANGELOG.rst
src/pup/__init__.py

Bumped version to 1.0.0a4.

---

src/pup/plugins/win/dist_layout_template/{{cookiecutter.app_name}} {{cookiecutter.version}}/{{cookiecutter.app_name}}.vbs

Fixed Windows launch script: now works if ran from other dirs.

---

setup.py
src/pup/context.py
src/pup/plugins/win/create_msi.py
src/pup/plugins/win/dist_layout.py
src/pup/plugins/win/msi_wsx_template/{{cookiecutter.app_name}} {{cookiecutter.version}} WiX/{{cookiecutter.app_name}} {{cookiecutter.version}}.wsx
src/pup/plugins/win/msi_wxs_template/{{cookiecutter.app_name}} {{cookiecutter.version}}.wix-sources/{{cookiecutter.app_name}} {{cookiecutter.version}}.wxs
src/pup/plugins/win/steps.py

Minimal Windows MSI packaging plugin implementation.

---

setup.py

Update PyPI classifiers.

---

setup.py

Updated direct dependency library versions.

---

README.rst

Updated README.

---

CHANGELOG.rst
README.rst
src/pup/__init__.py

Bumped version to 1.0.0a5.

---

src/pup/__main__.py
src/pup/api.py
src/pup/context.py
src/pup/plugins/mac/app_bundle.py
src/pup/plugins/mac/create_dmg.py
src/pup/plugins/win/create_msi.py
src/pup/plugins/win/dist_layout.py

Nice package name minimal implementation

---

src/pup/__main__.py
src/pup/api.py
src/pup/context.py
src/pup/plugins/mac/app_bundle.py
src/pup/plugins/mac/create_dmg.py
src/pup/plugins/mac/dmgbuild_settings_template/{{cookiecutter.app_name}}.dmgbuild/settings.py
src/pup/plugins/win/create_msi.py
src/pup/plugins/win/msi_wxs_template/{{cookiecutter.app_name}} {{cookiecutter.version}}.wix-sources/{{cookiecutter.app_name}} {{cookiecutter.version}}.wxs

Now using icons on macOS and Windows

---

src/pup/__main__.py
src/pup/api.py
src/pup/context.py
src/pup/plugins/mac/create_dmg.py
src/pup/plugins/mac/dmgbuild_settings_template/{{cookiecutter.app_name}}.dmgbuild/settings.py
src/pup/plugins/win/create_msi.py
src/pup/plugins/win/msi_wxs_template/{{cookiecutter.app_name}} {{cookiecutter.version}}.wix-sources/{{cookiecutter.app_name}} {{cookiecutter.version}}.wxs

Optional license agreement requirement

---

README.rst
docs/source/iat.rst
docs/source/toc.rst

Updated README: new capabilities and updated usage.

---

CHANGELOG.rst
src/pup/__init__.py

Bumped version to 1.0.0a6.

---

MANIFEST.in
docs/newsfragments/118.bug

Include missing bundled templates in PyPI packages.

---

CHANGELOG.rst
docs/newsfragments/118.bug
src/pup/__init__.py

Bumped version to 1.0.0a7.

---

docs/newsfragments/125.enhancement
src/pup/plugins/python_runtime.py

Python Standalone Build URL now overridable via env var.

---

docs/newsfragments/125.bug
src/pup/plugins/mac/create_dmg.py

macOS - Use absolute path when spawning dmgbuild

---

src/pup/context.py
src/pup/plugins/install_cleanup.py
src/pup/plugins/mac/app_bundle.py
src/pup/plugins/mac/steps.py
src/pup/plugins/python_runtime.py
src/pup/plugins/win/dist_layout.py
src/pup/plugins/win/steps.py

Addresses #128, changing the packaging sequence on both macOS and Windows.

Restructured package sequence: extract PBS before app dir template.

---

CHANGELOG.rst
docs/newsfragments/122.bug
docs/newsfragments/125.bug
docs/newsfragments/125.enhancement
src/pup/__init__.py

Bumped version to 1.0.0a8.

---

docs/newsfragments/140.enhancement
src/pup/plugins/mac/sign.py

Sign shared libs bundled in wheels bundled in app, on macOS.

---

CHANGELOG.rst
docs/newsfragments/138.bug
docs/newsfragments/140.enhancement
src/pup/__init__.py

Update version and release notes for 1.0.0a9.

---

docs/newsfragments/141.other
src/pup/plugins/mac/notarize.py
src/pup/plugins/mac/sign.py

No need to reinvent shutil.which on macOS.

---

CHANGELOG.rst
docs/newsfragments/141.other
docs/newsfragments/156.bug
src/pup/__init__.py

Bumped version to 1.0.0a10.

---

docs/newsfragments/147.other
docs/source/platform_notes/windows_msi.rst
src/pup/plugins/win/msi_wxs_template/{{cookiecutter.app_name}} {{cookiecutter.version}}.wix-sources/{{cookiecutter.app_name}} {{cookiecutter.version}}.wxs

Win MSI: no Start Menu directory.

---

docs/newsfragments/151.enhancement
docs/source/platform_notes/windows_msi.rst

Win MSI: docs on per-maching installing.

---

docs/newsfragments/103.enhancement
setup.py
src/pup/plugins/win/create_msi.py
src/pup/plugins/win/msi_wxs_template/{{cookiecutter.app_name}} {{cookiecutter.version}}.wix-sources/{{cookiecutter.app_name}} {{cookiecutter.version}}.wxs

Generate bitmaps with the given logo for Win MSI UI.

---

docs/newsfragments/153.enhancement
setup.py
src/pup/plugins/install_cleanup.py
src/pup/plugins/mac/app_bundle.py
src/pup/plugins/mac/app_bundle_template/{{cookiecutter.app_bundle_name}}.app/Contents/MacOS/launcher.c
src/pup/plugins/mac/app_bundle_template/{{cookiecutter.app_bundle_name}}.app/Contents/MacOS/{{cookiecutter.launcher_name}}
src/pup/plugins/mac/launcher.py
src/pup/plugins/mac/steps.py

macOS: use binary launcher instead of shell script.

---

CHANGELOG.rst
docs/newsfragments/103.enhancement
docs/newsfragments/145.enhancement
docs/newsfragments/147.other
docs/newsfragments/151.enhancement
docs/newsfragments/153.enhancement
docs/newsfragments/155.other
docs/newsfragments/169.other
src/pup/__init__.py

Bumped version to 1.0.0a11.

---

CHANGELOG.rst
docs/newsfragments/177.bug
src/pup/__init__.py

Bumped version to 1.0.0a12 + updated changelog.

---

docs/newsfragments/137.bug
src/pup/plugins/metadata.py

Package from PyPI too: don't assume source is local directory.

---

CHANGELOG.rst
README.rst
docs/newsfragments/137.bug
docs/newsfragments/150.enhancement
docs/newsfragments/185.bug
src/pup/__init__.py

Bumped version to 1.0.0a13 + updated changelog and readme.

---

MANIFEST.in
docs/190.bug

Fix packaging: bundle Linux AppImage template!

---

CHANGELOG.rst
docs/190.bug
src/pup/__init__.py

Bumped version to 1.0.0a14 + updated changelog.

---

README.rst

195 docs for pyflags

---

CHANGELOG.rst
docs/newsfragments/195.bug
src/pup/__init__.py

Bumped version to 1.0.0a15 + updated changelog.

---

docs/newsfragments/202.enhancement
src/pup/plugins/python_runtime.py

Added 3.9 and 3.10 PBS support + updated 3.8.

---

CHANGELOG.rst
docs/newsfragments/201.bug
docs/newsfragments/202.enhancement
src/pup/__init__.py

Bumped version to 1.0.0a16.

---

docs/newsfragments/208.enhancement
docs/source/platform_notes/index.rst
docs/source/platform_notes/linux_appimage.rst
src/pup/plugins/linux/appdir_create.py
src/pup/plugins/linux/appdir_layout.py

208 appimage override tool url

---

src/pup/context.py
src/pup/plugins/metadata.py
src/pup/plugins/pip_install.py

30 reuse metadata wheel

---

docs/newsfragments/30.other

Now completing the changes in #30.

Added missing newsfragment.

---

docs/newsfragments/214.enhancement
src/pup/__main__.py
src/pup/api.py
src/pup/context.py
src/pup/plugins/python_runtime.py

New package --python-version CLI option.

---

docs/newsfragments/211.enhancement

Outstanding newsfragment for #211.

Adding a newsfragment.

---

src/pup/plugins/mac/icon_from_png.py
src/pup/plugins/win/icon_from_png.py

Fix silly failure in the context of #211.

Don't fail when no --icon-path is given!

---

setup.py

Updated direct dependency versions.

---

docs/newsfragments/220.other

...missing from PR #222, addressing #220.

Added newsfragment.

---

docs/newsfragments/123.enhancement
setup.py
src/pup/context.py
src/pup/plugins/metadata.py

Collect packaging parameters from the project's wheel metadata.

---

src/pup/context.py
src/pup/plugins/metadata.py

123 improvements

---

src/pup/plugins/download.py

225 fix download redirects

---

docs/newsfragments/209.enhancement
src/pup/dispatcher.py
src/pup/plugins/linux/appdir_create.py
src/pup/spawn.py

209 version in appimage filename

---

CHANGELOG.rst
docs/newsfragments/123.enhancement
docs/newsfragments/208.enhancement
docs/newsfragments/209.enhancement
docs/newsfragments/211.enhancement
docs/newsfragments/214.enhancement
docs/newsfragments/220.other
docs/newsfragments/30.other
src/pup/__init__.py

Bumped version to 1.0.0a17.

---

docs/newsfragments/239.bug
docs/source/platform_notes/windows_msi.rst

Fixed Windows platform docs: had a spurious quote in there!
